apiVersion: apps/v1
kind: Deployment
metadata:
  name: wild-cabaret-api-python
  namespace: superminds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wild-cabaret-api-python
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wild-cabaret-api-python
    spec:
      containers:
        - name: booking
          image: registry.digitalocean.com/fabs/wild-cabaret-api-python:${{ env.IMAGE_TAG }}
          ports:
            - name: http
              containerPort: 8080
      