apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildcabaret-api-python
  namespace: superminds
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: wildcabaret-api-python
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wildcabaret-api-python
    spec:
      containers:
        - name: wildcabaret-api-python
          image: registry.digitalocean.com/superminds/wildcabaret-api-python:${{ env.IMAGE_TAG }}
          ports:
            - name: http
              containerPort: 8080
      
