apiVersion: v1
kind: Service
metadata:
  name: wildcabaret-api-python
  namespace: superminds
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: wildcabaret-api-python